import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendSummaryEmail(summary, groupName) {
  const { error } = await resend.emails.send({
    from: "FB Group Watcher <onboarding@resend.dev>",
    to: process.env.RECIPIENT_EMAIL,
    subject: `Facebook Group Summary: ${groupName}`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #1877f2; border-bottom: 2px solid #1877f2; padding-bottom: 10px;">
          ${groupName}
        </h1>
        <div style="line-height: 1.6; color: #333;">
          ${markdownToHtml(summary)}
        </div>
        <footer style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px;">
          Generated by FB Group Watcher
        </footer>
      </div>
    `,
  });

  if (error) {
    throw new Error(`Failed to send email: ${error.message}`);
  }
}

function markdownToHtml(markdown) {
  return markdown
    .replace(/^### (.*$)/gim, "<h3>$1</h3>")
    .replace(/^## (.*$)/gim, "<h2>$1</h2>")
    .replace(/^# (.*$)/gim, "<h1>$1</h1>")
    .replace(/^\* (.*$)/gim, "<li>$1</li>")
    .replace(/^- (.*$)/gim, "<li>$1</li>")
    .replace(/\*\*(.*)\*\*/gim, "<strong>$1</strong>")
    .replace(/\*(.*)\*/gim, "<em>$1</em>")
    .replace(/(<li>.*<\/li>)/s, "<ul>$1</ul>")
    .replace(/\n/gim, "<br>");
}
